
#ifndef __IR_DATA_H__
#define __IR_DATA_H__

const int8_t IR_ARGS[IR_INVALID_OPCODE] = {
	0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1,
	1, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2,
	0, 0, 1, 2,
};

const char *IR_STRINGS[IR_INVALID_OPCODE] = {
	"NOP",
	"IMM",
	"IMM_PROG_OFFSET",
	"IMM_32",
	"IMM_32_SEC",
	"IMM_8",
	"PUSH",
	"PUSH_SEC",
	"PUSH_TER",
	"PUSH_IMM",
	"PUSH_32",
	"PUSH_IMM_32",
	"POP",
	"POP_SEC",
	"POP_TER",
	"POP_32",
	"EX_SEC_PRI",
	"CALL",
	"ADJ",
	"ENTER",
	"LEAVE",
	"EXIT",
	"STORE_LOCAL",
	"STORE_GLOBAL",
	"LEA_LOCAL",
	"LEA_GLOBAL",
	"LOAD_CHAR",
	"LOAD_WORD",
	"LOAD_INT",
	"LOAD_LONG",
	"COMPARE_Z",
	"COMPARE_NZ",
	"LOR",
	"LAND",
	"NOT",
	"OR",
	"XOR",
	"AND",
	"COMPARE_EQ",
	"COMPARE_NEQ",
	"COMPARE_LT",
	"COMPARE_GT",
	"COMPARE_LTEQ",
	"COMPARE_GTEQ",
	"SHL",
	"SHR",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"NEG",
	"INC",
	"INC_SEC",
	"INC_TER",
	"DEC",
	"DEC_SEC",
	"DEC_TER",
	"OR_CONST",
	"XOR_CONST",
	"AND_CONST",
	"COMPARE_EQ_CONST",
	"COMPARE_NEQ_CONST",
	"COMPARE_LT_CONST",
	"COMPARE_GT_CONST",
	"COMPARE_LTEQ_CONST",
	"COMPARE_GTEQ_CONST",
	"SHL_CONST",
	"SHR_CONST",
	"ADD_CONST",
	"SUB_CONST",
	"MUL_CONST",
	"DIV_CONST",
	"MOD_CONST",
	"JMP",
	"BZ",
	"BNZ",
	"STRLEN",
	"STRCPY",
	"STORE",
	"SET_ONE_IF_NOT_ZERO",
	"DEFINE_FUNCTION",
	"PUSH_ARG",
	"PUSH_ARG_32",
	"PUSH_ARG_IMM",
	"PUSH_ARG_IMM_32",
};


#endif